// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDlnUbmSguloSQ5fJLKZOeUbv94kToKc',
    appId: '1:171947294057:web:013295d6c3ace611d511f8',
    messagingSenderId: '171947294057',
    projectId: 'trello-2-f85a2',
    authDomain: 'trello-2-f85a2.firebaseapp.com',
    storageBucket: 'trello-2-f85a2.appspot.com',
    measurementId: 'G-C7LZLL52F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdHz0foR-6WQT0iv8wVzIu7IExILOibWs',
    appId: '1:171947294057:android:19705b93721dd51ed511f8',
    messagingSenderId: '171947294057',
    projectId: 'trello-2-f85a2',
    storageBucket: 'trello-2-f85a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByH-PZRjdisMK0HJM-fFIrn9UygAzYGgU',
    appId: '1:171947294057:ios:d27cdc5ed7589a5fd511f8',
    messagingSenderId: '171947294057',
    projectId: 'trello-2-f85a2',
    storageBucket: 'trello-2-f85a2.appspot.com',
    iosBundleId: 'com.tryc.openproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByH-PZRjdisMK0HJM-fFIrn9UygAzYGgU',
    appId: '1:171947294057:ios:0fa6fb380a1f6c71d511f8',
    messagingSenderId: '171947294057',
    projectId: 'trello-2-f85a2',
    storageBucket: 'trello-2-f85a2.appspot.com',
    iosBundleId: 'com.example.openProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPDlnUbmSguloSQ5fJLKZOeUbv94kToKc',
    appId: '1:171947294057:web:57525b1be87194c0d511f8',
    messagingSenderId: '171947294057',
    projectId: 'trello-2-f85a2',
    authDomain: 'trello-2-f85a2.firebaseapp.com',
    storageBucket: 'trello-2-f85a2.appspot.com',
    measurementId: 'G-WRC656KS0L',
  );
}
